### ISSUE TITLE
Ngrx version?

### ISSUE THREAD

**Issue by HomeboxJim** [mkusz/ng2_websockets_quickstart#1]
Hey, nice example! 

It would be interesting to see a simple example like this but that uses ngrx/store and ngrx/effects. I am very confused about how to handle websockets in an Angular 2 app that uses the ngrx Redux state management pattern. :/

**Comment by mkusz** [comment]
Since this code was just a prove of concept just to discover if it's possible and I'm not using ng2 right now (it's the reason why this comment is so late), I'm not able to provide you a requested example.
